### ISSUE TITLE
Can't install NielsenAppSDK from CocoaPods

### ISSUE THREAD

**Issue by iDevid** [NielsenDigitalSDK/nielsenappsdk-ios-specs-dynamic#1]
When I try to run "pod install" with your repo I get this error:
![schermata 2019-02-19 alle 16 07 32](https://user-images.githubusercontent.com/1254022/53025069-92729b80-3460-11e9-8e1c-a7b1419d6a23.png)

**Comment by jcislinsky** [comment]
+1 🤯

**Comment by jaggsu01** [comment]
Hi Folks,
Did you put the proper credentials in .netrc file to pull the repo. If you do not have the credentials, please ask your Nielsen representative to provide you that and you should be good.

**Comment by iDevid** [comment]
The crediantials appears on the website, I used that but the download doesn't work

**Comment by jaggsu01** [comment]
Hi Davide Sibilio, 
Did you try it today also, and what is the cocoapods version are you using. I hope you are following steps mentioned here https://engineeringportal.nielsen.com/docs/Digital_Measurement_iOS_Artifactory_Guide

**Comment by iDevid** [comment]
Yes, of course, I tried 10 minutes ago with the last version of CocoaPods

**Comment by jaggsu01** [comment]
No Issues, let us take a look at it and we will respond back. Thanks for your patience !!

**Comment by iDevid** [comment]
I can give you my token if you want to find the bug

**Comment by jaggsu01** [comment]
Please mail me at suraj.jagga@nielsen.com

**Comment by jaggsu01** [comment]
Nielsen Italy representative will reach out to you to unblock you.
