### ISSUE TITLE
Impossible to download the zip file form cocoa pods. 404

### ISSUE THREAD

**Issue by DrAma999** [NielsenDigitalSDK/nielsenappsdk-ios-specs-dynamic#5]
Hello,
I have the .netrc file containing username and password but it seems that I'm not able to download the sdk anymore.
Once I launch the `pod install` command I get:
```
Installing NielsenAppSDK (8.0.0.0)

[!] Error installing NielsenAppSDK
[!] /usr/bin/curl -f -L -o /var/folders/4y/6qm7y18s0jv2h3lzf734137m0000gp/T/d20220304-36322-1b37cbd/file.zip https://raw.githubusercontent.com/nielsendigitalsdk/nielsenappsdk-ios-dynamic/master/iOS/Global/NielsenAppSDK-8.0.0.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.2 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
```
I'd like to point out that this issue happened recently because I remember I've successfully downloaded it the beginning of this week.

**Comment by DrAma999** [comment]
Solved removing the .netrc

**Comment by taylornzme** [comment]
Hi, What did you remove from .netrc? I am experiencing the same issue.

**Comment by DrAma999** [comment]
> Hi, What did you remove from .netrc? I am experiencing the same issue.

Since I had just one entry I removed the file itself

**Comment by taylornzme** [comment]
Thank you so much @DrAma999!

**Comment by majindageta** [comment]
Just adding (for anyone who doesn't remember) your `.netrc` file is in your home folder (or can be)
Thank you @DrAma999 for the fix.

Was this caused by the cocoa pods update? is the only thing i changed seems last time it worked.
