### ISSUE TITLE
pod update error

### ISSUE THREAD

**Issue by seraph3b** [NielsenDigitalSDK/nielsenappsdk-ios-specs-dynamic#6]
Hi,
yesterday I tryed to update pod but it gave me this error installing 8.2.0.0 (this appens forcing 8.1.0.0 too):

[!] Error installing NielsenAppSDK
[!] /usr/bin/curl -f -L -o /var/folders/90/tb_8cwd51091kzd8bjj9nlhw0000gn/T/d20220322-954-1xrg82u/file.zip https://raw.githubusercontent.com/nielsendigitalsdk/nielsenappsdk-ios-dynamic/master/iOS/Global/NielsenAppSDK-8.2.0.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404

pod version 1.11.3, macos 12.3, xcode 13.3

thanks for your support

**Comment by seraph3b** [comment]
problem solved, just removed credential from .netrc

**Comment by taylornzme** [comment]
Hi, What did you remove from .netrc? I am experiencing the same issue.
